### ISSUE TITLE
Is it possible to allow IdeaVIM to work with buffer ?

### ISSUE THREAD

**Issue by ocoka** [nd/tui#2]
Hi, thank you for such convenient plugin, I like it.
But for peaople, who used to VIM movement it confusing that no movement action available within the text buffer used to represent directory structure, is it possible to allow VIM plugin to work like as with standard readonly text file ?

**Comment by nd** [comment]
Please ask in [ideavim](https://github.com/JetBrains/ideavim) tracker. I don't use it myself.
